### ISSUE TITLE
20190724 Gophers Code Reading Party

### ISSUE THREAD

**Issue by izumin5210** [wantedly/gophers-code-reading-party#17]
201907241900 ~ @ 5F Lounge, Wantedly, Inc. Tokyo HQ

## WHY
Go 完全に理解したい

## WHAT
とりあえず読みたいものを書いていきましょう！

**Comment by izumin5210** [comment]
monday 読みたい https://github.com/eko/monday
https://github.com/wantedly/microservices_monday/issues/50#issuecomment-514024543

設定ファイルまわりのセンスが良い
一方で、自分たちが活用するにはもう少し機能が足りない
どういうアーキテクチャ・実装になってるかをみて、contribute or fork したい

**Comment by izumin5210** [comment]
Project -> 起動したいアプリケーション・forward してきたいアプリケーションの集合

e.g.

```yaml
projects:
# people/updates の開発では yashima-updates 及び yashima-updates-contents に
# 手を入れることが多いので、それらをローカルで起動。
# また、これら2サービスは accounts と options にも依存するため、
# この2つを開発用クラスタから port-forward してくる
- name: people/updates
  local:
  - *yashima-updates-local
  - *yashima-updates-contents-local
  forward:
  - *accounts-k8s
  - *options-k8s

# visit/project の開発では...（以下略
- name: visit/project
  local:
  - *visit-project-server-local
  - *visit-admin-frontend-local
  forward:
  - *wantedly-k8s
  - *users-rails-k8s
```

起動に sudo が必要なのは `/etc/hosts` を書き換えるから。
[txeh](https://github.com/txn2/txeh) というパッケージで実現している。
ただ、この sudo で起動したプロセスで rails server とかを起動することになるため、root 権限を持つサーバが立つことになる。

コードは全体的に素直で読みやすい。たまに `go` つけ忘れているところがある。

## Forwarder

forwarder の起動 https://github.com/eko/monday/blob/v1.0.0/pkg/forwarder/forwarder.go#L104-L217

面白いのは `kubernetes-remtoe` といわれている forwarder。簡易版の telepresence のような動きをする。
https://github.com/eko/monday/wiki/Configuration#type-kubernetes-remote
https://github.com/eko/monday/blob/v1.0.0/pkg/forwarder/kubernetes/forwarder.go

対象になる deployment の container を [monday-proxy](https://hub.docker.com/r/ekofr/monday-proxy) ([Dockerfile](https://github.com/eko/monday/blob/v1.0.0/docker-proxy/Dockerfile))というイメージのものに置き換えてしまう
https://github.com/eko/monday/blob/v1.0.0/pkg/forwarder/kubernetes/forwarder.go#L230-L270
置き換えた pod の中では sshd が動いており、そこにむかって `ssh -R` でつなぎに行くことで、k8s 上のトラフィックを手元に流し込んでいる
https://github.com/eko/monday/blob/v1.0.0/pkg/forwarder/ssh/forwarder.go#L52-L89
